sudo: required
services:
  - docker

before_install:
  - docker build -t apakina/docker-react3 -f Dockerfile.dev .

#script:
#  - docker run apakina/docker-react3 npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: apakina-react
  env: ApakinaReact-env
  bucket_name: "elasticbeanstalk-us-east-2-136935711337"
  bucket_path: "apakina-react-builds"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
